.PHONY: clean All

All:
	@echo "----------Building project:[ UOCCoworking - Menu ]----------"
	@"$(MAKE)" -f  "UOCCoworking.mk"
clean:
	@echo "----------Cleaning project:[ UOCCoworking - Menu ]----------"
	@"$(MAKE)" -f  "UOCCoworking.mk" clean
